name = input("请输入您的姓名")
age = input("请输入您的年龄")
sexxy = input("请输入您的性别")
high = float(input("请输入您的身高"))
weight = float(input("请输入体重"))
ID_number = int(input("请输入身份证号码"))
education = input("请输入您的学历")
birthday = input("请输入您的出生年月")
addr = input("请输入您的家庭住址")
tell = int(input("请输入电话号码"))
case = input("请输入职位")
money = int(input("请输入薪水"))

print("职位%s\nmoney%d\n身高%f\n"%(case,money,high))

